AppDebug: true   # 设置程序所处的模式，debug=true 调试模式，日志优先显示在控制台， debug=false 非调试模式，将写入日志文件

HttpServer:
  Api:
    Port: ":8080"                 #门户网站类端口,注意前面有冒号
Lock:
  Type: "Distributed" # Local或Distributed
  Distributed:
      RedisAddr: "39.105.20.187:6379"
      Password: "qwer1234"
